AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: |
  AWS
  Sample SAM Template for AWS
  logs levels | numeric value ------------------------------ CRITICAL    | 50 ERROR       | 40 WARNING     | 30 INFO        | 20 DEBUG       | 10 NOTSET      | 0
Mappings:
  logLevel:
    dev:
      level: '10'
    test:
      level: '20'
    stage:
      level: '20'
    prod:
      level: '20'
  DynamoDb:
    dev:
      ddbLapTable: dashboard-test
    test:
      ddbLapTable: dashboard-test
    stage:
      ddbLapTable: cars-live-status
    prod:
      ddbLapTable: cars-live-status
Globals:
  Function:
    Timeout: !Ref recourseTimeOut
    Environment:
      Variables:
        apiGetAwayName: griiip_api
        logLevel: !FindInMap
          - logLevel
          - !Ref Env
          - level
        common_mappings: serverless.common.yml:custom
        griiip_api_url: !Ref griiipApiUrl
        griiip_api_key: !Ref apiGetAwayKey
        cache_ddb_table_name: !Ref cashTable
        cache_ddb_table_key: prefix_lap_id
        my_sql_host: !Ref MySqlHost
        my_sql_user: !Ref MySqlUser
        my_sql_pass: !Ref MySqlPass
        my_sql_db: !Ref MySqlSchma
        rds_connection_pull_size: !Ref RdsConnPoolSize
        Region: !Ref Region
        AccountId: !Ref AccountId
Resources:
  producer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join ["",[!Ref StackTagName, "-producer-", !Ref EnvironmentTagName]]
      Description: !Join ["Stack",[!Ref StackTagName, "Environment", !Ref EnvironmentTagName, "Function Resources"]]
      CodeUri: .
      AutoPublishAlias: Live
      Handler: src.producer.producer_lambda.lambda_handler
      Runtime: python3.7
      MemorySize: 3008
      Timeout: 300
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - SQSSendMessagePolicy:
            QueueName: !GetAtt ProcessLapsProducerToConsumer.QueueName
        - DynamoDBCrudPolicy:
            TableName: !Ref cashTable
      Environment:
        Variables:
          logLevel: !FindInMap
            - logLevel
            - !Ref Env
            - level
          QUEUE_NAME: !GetAtt ProcessLapsProducerToConsumer.QueueName
          QUEUE_ARN: !GetAtt ProcessLapsProducerToConsumer.Arn
          QUEUE_URL: !Ref ProcessLapsProducerToConsumer
          TABLE_NAME: !Ref cashTable #!Join ["",[!Ref StackTagName, "-cashTable-", !Ref EnvironmentTagName]] #!Ref cashTable
          TABLE_ARN: !GetAtt cashTable.Arn
      Events:
        ProcessLapApiGatewayANYnewLap:
          Type: Api
          Properties:
            Path: /newLap
            Method: ANY
            RestApiId: !Ref ProcessLapApiGateway
      DeploymentPreference:
        Type: AllAtOnce
  ProcessLapUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      ApiStages:
        - ApiId: !Ref ProcessLapApiGateway
          Stage: !Ref ProcessLapApiGateway.Stage
      Description: Use Plan for lambda base process lap
      UsagePlanName: !Join ["",[!Ref StackTagName, "-api-plan-", !Ref EnvironmentTagName]]
  ProcessLapApiKey:
    Type: AWS::ApiGateway::ApiKey
    DependsOn:
      - ProcessLapUsagePlan
    Properties:
      Enabled: true
      Name: !Join ["",[!Ref StackTagName, "-api-key-", !Ref EnvironmentTagName]]
      StageKeys:
        - RestApiId: !Ref ProcessLapApiGateway
          StageName: !Ref ProcessLapApiGateway.Stage
  processLapUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    DependsOn:
      - ProcessLapApiKey
      - ProcessLapUsagePlan
    Properties:
      KeyId: !Ref ProcessLapApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref ProcessLapUsagePlan
  ProcessLapApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Join ["",[!Ref StackTagName, "-api-", !Ref EnvironmentTagName]]
      StageName: !Ref Env
      Cors: '''*'''
      Auth:
        ApiKeyRequired: true

      EndpointConfiguration: REGIONAL
      TracingEnabled: true
  ProcessLapsProducerToConsumer:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join ["",[!Ref StackTagName, "-ProducerToConsumer-", !Ref EnvironmentTagName]]
      VisibilityTimeout: !Ref recourseTimeOut
  sessionEnd:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join ["",[!Ref StackTagName, "-sessionEnd-", !Ref EnvironmentTagName]]
      AutoPublishAlias: Live
      Description: !Join ["Stack",[!Ref StackTagName, "Environment", !Ref EnvironmentTagName, "Function sessionEnd"]]
      CodeUri: .
      Handler: src.sessionEnd.session_end_lambda.lambda_handler
      Runtime: python3.7
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - SQSSendMessagePolicy:
            QueueName: !GetAtt ProcessLapsProducerToConsumer.QueueName
      Events:
        ProcessLapApiGatewayANYsessionEnd:
          Type: Api
          Properties:
            Path: /sessionEnd
            Method: ANY
            RestApiId: !Ref ProcessLapApiGateway
      Environment:
        Variables:
          driverLapFiledsToQuery: 'lapStartDate, TrackId, lapName, CarId, UserId'
          driverLapsTable: driverlaps
          QUEUE_NAME: !GetAtt ProcessLapsProducerToConsumer.QueueName
          QUEUE_ARN: !GetAtt ProcessLapsProducerToConsumer.Arn
          QUEUE_URL: !Ref ProcessLapsProducerToConsumer
          logLevel: !FindInMap
            - logLevel
            - !Ref Env
            - level
  consumer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join ["",[!Ref StackTagName, "-consumer-", !Ref EnvironmentTagName]]
      Description: !Join ["Stack",[!Ref StackTagName, "Environment", !Ref EnvironmentTagName, "Function consumer"]]
      CodeUri: .
      Handler: src.consumer.consumer_lambda.lambda_handler
      Runtime: python3.7
      MemorySize: 3008
      Timeout: 300
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
        - SQSPollerPolicy:
            QueueName: !GetAtt ProcessLapsProducerToConsumer.QueueName
        - LambdaInvokePolicy:
            FunctionName: !Ref KpiLambda
      Environment:
        Variables:
          CalcKpiFor: !Ref CalcKpiFor
          logLevel: !FindInMap
            - logLevel
            - !Ref Env
            - level
          MAX_ACC_PERCENT: 0.8
          FULL_LAP_FLOOR: 0.9
          FULL_LAP_CELL: 1.03
          PART_LAP_FLOOR: 0.1
          runDataRetrieveLimit: 5000
          runDataPaging: 1
          ddb_lap_table: !FindInMap
            - DynamoDb
            - !Ref Env
            - ddbLapTable
          ddb_lap_table_key: lap_id
          year_prefix: 20
          kpi_num_of_points: 5
          KpiLambda: !Ref KpiLambda
      Events:
        ProcessLapsProducerToConsumer:
          Type: SQS
          Properties:
            Queue: !GetAtt ProcessLapsProducerToConsumer.Arn
            BatchSize: 1
      AutoPublishAlias: Live
      DeploymentPreference:
        Type: AllAtOnce
  cashTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join ["",[!Ref StackTagName, "-cashTable-", !Ref EnvironmentTagName]]
      AttributeDefinitions:
        - AttributeName: 'prefix_lap_id'
          AttributeType: S
        - AttributeName: 'lap_number'
          AttributeType: S
      BillingMode: PROVISIONED
      KeySchema:
        - AttributeName: 'prefix_lap_id'
          KeyType: HASH
        - AttributeName: 'lap_number'
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
  producerScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MinCapacity: 1
      MaxCapacity: 20
      ResourceId: !Sub function:${producer}:Live
      RoleARN: !Sub "arn:aws:iam::${AWS::AccountId}:role/aws-service-role/lambda.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_LambdaConcurrency"
      ScalableDimension: lambda:function:ProvisionedConcurrency
      ServiceNamespace: lambda
    DependsOn: producerAliasLive
  producerScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: utilization
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref producerScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 0.7
        PredefinedMetricSpecification:
          PredefinedMetricType: LambdaProvisionedConcurrencyUtilization
  consumerScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MinCapacity: 1
      MaxCapacity: 30
      ResourceId: !Sub function:${consumer}:Live
      RoleARN: !Sub "arn:aws:iam::${AWS::AccountId}:role/aws-service-role/lambda.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_LambdaConcurrency"
      ScalableDimension: lambda:function:ProvisionedConcurrency
      ServiceNamespace: lambda
    DependsOn: consumerAliasLive
    #DependsOn: consumer
  consumerScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: utilization
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref consumerScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 0.7
        PredefinedMetricSpecification:
          PredefinedMetricType: LambdaProvisionedConcurrencyUtilization
Parameters:
  Region:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/Region
  AccountId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/AccountId
  recourseTimeOut:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/recourseTimeOut
  griiipApiUrl:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/griiipApiUrl
  apiGetAwayKey:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/apiGetAwayKey
  MySqlHost:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/MySqlHost
  MySqlUser:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/MySqlUser
  MySqlPass:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/MySqlPass
  MySqlSchma:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/MySqlSchma
  RdsConnPoolSize:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/RdsConnPoolSize
  CalcKpiFor:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/CalcKpiFor
  KpiLambda:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/KpiLambda
  Env:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/Env
  StackTagName:
    Type: String
    Description: Stack Name (injected by Stackery at deployment time)
    Default: processLap
  EnvironmentTagName:
    Type: String
    Description: Environment Name (injected by Stackery at deployment time)
    Default: test